---
- name: Configure webserver with nginx and tls
  hosts: webservers
  become: True
  vars:
      key_file: /etc/nginx/ssl/nginx.key
      cert_file: /etc/nginx/ssl/nginx.crt
      conf_file_path: /etc/nginx/sites-available/default
      server_name: localhost
  tasks:
      - name: install nginx
        yum: name=nginx update_cache=yes

      - name: create directories for ssl certificates
        file: path=/etc/nginx/ssl state=directory

      - name: copy tls key
        copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
        notify: restart nginx

      - name: copy tls certificate
        copy: src=files/nginx.crt dest={{ cert_file }}
        notify: restart nginx

      - name: copy nginx config file
        template: src=templates/nginx.conf.j2 dest={{ conf_file_path ~ "/nginx.conf" }}
        #copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
        notify: restart nginx

      - name: enable configuration
        file: >
            dest=/etc/nginx/sites-enabled/default/nginx.conf
            src={{ conf_file_path }}
            state=link
        notify: restart nginx

      - name: copy index.html
        template:
            src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
            mode=0644
  handlers:
      - name: restart nginx
        service: name=nginx state=restarted
